name: .NET

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore
      run: dotnet restore src/ProductOperationsManager/ProductOperationsManager.sln

    - name: Build
      run: dotnet build src/ProductOperationsManager/ProductOperationsManager.sln --no-restore

    - name: Test
      run: dotnet test src/ProductOperationsManager/ProductOperationsManager.sln --no-build